# Generated by Django 6.1.1 on 2026-09-18 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCrew',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('PLUMBING', 'Plumbing & Water Supply'), ('ELECTRICAL', 'Electrical & Lighting'), ('SANITATION', 'Sanitation & Waste Management'), ('CIVIL', 'Civil Infrastructure & Roads'), ('SAFETY', 'Public Safety & Hazards'), ('GENERAL', 'General Administration')], default='GENERAL', max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('active_tasks_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('PLUMBING', 'Plumbing & Water Supply'), ('ELECTRICAL', 'Electrical & Lighting'), ('SANITATION', 'Sanitation & Waste Management'), ('CIVIL', 'Civil Infrastructure & Roads'), ('SAFETY', 'Public Safety & Hazards'), ('GENERAL', 'General Administration')], default='GENERAL', max_length=50)),
                ('campus_zone', models.CharField(blank=True, default='', help_text='e.g. Hostel Block B, Library, Cafeteria', max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('base_severity', models.IntegerField(default=1, help_text='AI evaluated initial severity (1-10)')),
                ('crowd_report_count', models.PositiveIntegerField(default=1, help_text='Number of students/citizens reporting this')),
                ('computed_priority', models.FloatField(default=1.0, help_text='Crowd & recency weighted urgency score')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('QUEUED', 'Queued in Triage'), ('ASSIGNED', 'Assigned to Crew'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved (Pending Confirmation)'), ('CLOSED', 'Confirmed & Closed'), ('REOPENED', 'Reopened by Citizen'), ('REJECTED', 'Rejected / Spam')], default='SUBMITTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='complaints.maintenancecrew')),
            ],
            options={
                'ordering': ['-computed_priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_identifier', models.CharField(blank=True, default='anonymous_user', max_length=255)),
                ('user_trust_score', models.FloatField(default=1.0, help_text='User reputation score (0.0 to 1.0)')),
                ('raw_text', models.TextField(help_text="Plain-text problem description in user's own words")),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('compressed_image', models.ImageField(blank=True, null=True, upload_to='uploads/compressed/%Y/%m/%d/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('campus_zone', models.CharField(blank=True, default='', help_text='Building or Zone Name', max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('department', models.CharField(choices=[('PLUMBING', 'Plumbing & Water Supply'), ('ELECTRICAL', 'Electrical & Lighting'), ('SANITATION', 'Sanitation & Waste Management'), ('CIVIL', 'Civil Infrastructure & Roads'), ('SAFETY', 'Public Safety & Hazards'), ('GENERAL', 'General Administration')], default='GENERAL', max_length=50)),
                ('initial_severity', models.IntegerField(default=5, help_text='AI estimated severity 1-10')),
                ('blur_score', models.FloatField(default=0.0)),
                ('is_valid_image', models.BooleanField(default=True)),
                ('yolo_detections', models.JSONField(blank=True, default=dict)),
                ('gemini_analysis', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('QUEUED', 'Queued in Triage'), ('ASSIGNED', 'Assigned to Crew'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved (Pending Confirmation)'), ('CLOSED', 'Confirmed & Closed'), ('REOPENED', 'Reopened by Citizen'), ('REJECTED', 'Rejected / Spam')], default='SUBMITTED', max_length=30)),
                ('is_confirmed_by_reporter', models.BooleanField(blank=True, help_text='True if reporter confirms fix, False if reopened', null=True)),
                ('reporter_feedback', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='complaints.complaintcluster')),
                ('assigned_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='complaints.maintenancecrew')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='complaints__status_f077e8_idx'), models.Index(fields=['campus_zone', 'status'], name='complaints__campus__ab548d_idx'), models.Index(fields=['latitude', 'longitude'], name='complaints__latitud_7c96e8_idx')],
            },
        ),
    ]
