# Generated by Django 6.1.1 on 2026-09-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='campus_zone',
            field=models.CharField(blank=True, default='Main Campus', help_text='Building or Zone Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='complaintcluster',
            name='campus_zone',
            field=models.CharField(blank=True, default='Main Campus', help_text='e.g. Hostel Block B, Library, Cafeteria', max_length=150),
        ),
    ]
