# Generated by Django 6.1.1 on 2026-09-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_campus_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_department',
            field=models.CharField(choices=[('PLUMBING', 'Plumbing & Water Supply'), ('ELECTRICAL', 'Electrical & Lighting'), ('SANITATION', 'Sanitation & Waste Management'), ('CIVIL', 'Civil Infrastructure & Roads'), ('SAFETY', 'Public Safety & Hazards'), ('GENERAL', 'General Administration')], default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_description',
            field=models.TextField(blank=True, default='', help_text="Plain-text problem description in user's own words"),
        ),
        migrations.AddField(
            model_name='complaint',
            name='detected_class',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='severity_score',
            field=models.IntegerField(default=5, help_text='AI estimated severity 1-10'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='yolo_confidence',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='raw_text',
            field=models.TextField(blank=True, default='', help_text="Plain-text problem description in user's own words"),
        ),
    ]
