# Generated by Django 5.2.17 on 2026-09-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_ai_summary_complaint_assigned_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='committee_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='complaint',
            name='faculty_supervisor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student_lead',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='complaintcluster',
            name='committee_notes',
            field=models.TextField(blank=True, default='', help_text='Notes and directives from oversight committee'),
        ),
        migrations.AddField(
            model_name='complaintcluster',
            name='faculty_supervisor',
            field=models.CharField(blank=True, default='', help_text='Designated teacher / faculty mentor', max_length=200),
        ),
        migrations.AddField(
            model_name='complaintcluster',
            name='student_lead',
            field=models.CharField(blank=True, default='', help_text='Student observer / council lead', max_length=200),
        ),
    ]
