# Generated by Django 5.2.17 on 2026-09-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING_VERIFICATION', 'Pending Manual Verification'), ('QUEUED', 'Queued in Triage'), ('ASSIGNED', 'Assigned to Crew'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved (Pending Confirmation)'), ('CLOSED', 'Confirmed & Closed'), ('REOPENED', 'Reopened by Citizen'), ('REJECTED', 'Rejected / Spam')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintcluster',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING_VERIFICATION', 'Pending Manual Verification'), ('QUEUED', 'Queued in Triage'), ('ASSIGNED', 'Assigned to Crew'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved (Pending Confirmation)'), ('CLOSED', 'Confirmed & Closed'), ('REOPENED', 'Reopened by Citizen'), ('REJECTED', 'Rejected / Spam')], default='SUBMITTED', max_length=30),
        ),
    ]
